### ISSUE TITLE
how to use a different port to 80 for the portal

### ISSUE THREAD

**Issue by mjtrini** [alanswx/ESPAsyncWiFiManager#106]
Hello,

Is there a way to set a different port for the configuration portal? For example if I want to use port 50, how can this be set? In my case the portal address would become 192.168.4.1:50

Regards,
Michael.

**Comment by romkey** [comment]
Your program creates the web server, the `AsyncWiFiManager` does not. When you instantiate an `AsyncWiFiManager` object, you pass it a web server object that you create like this:
```
AsyncWebServer server(80);
```
Change the `80` to the port number you want to use.

Please see the documentation for [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer) for more information.

**Comment by mjtrini** [comment]
Thanks!
