### ISSUE TITLE
Set HostName

### ISSUE THREAD

**Issue by albydnc** [alanswx/ESPAsyncWiFiManager#16]
How can I set the hostname? calling the classic WiFi.setHostname("name"); is not working.

**Comment by debsahu** [comment]
Use this instead `wifi_station_set_hostname(const_cast<char*>(HOSTNAME));` from sdk, out it before AsyncWiFiManager initialization in setup(). Define HOSTNAME globally as `const char HOSTNAME[] = "name";`
