### ISSUE TITLE
Compiler error after latest Arduino update to the latest code

### ISSUE THREAD

**Issue by dmytro-nff** [alanswx/ESPAsyncWiFiManager#26]
Hi!
Your example AutoConnect.ino compile with errors:
In file included from C:\Users\---\Documents\Arduino\libraries\ESPAsyncWiFiManager-master\ESPAsyncWiFiManager.h:21:0,

                 from C:\Users\---\Documents\Arduino\libraries\ESPAsyncWiFiManager-master\ESPAsyncWiFiManager.cpp:14:

C:\Users\---\Documents\Arduino\libraries\ESPAsyncWiFiManager-master\ESPAsyncWiFiManager.cpp: In member function 'void AsyncWiFiManager::startWPS()':

C:\Users\---\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_wps.h:86:1: error: C99 designator 'manufacturer' outside aggregate initializer
 }
 ^
C:\Users\---\Documents\Arduino\libraries\ESPAsyncWiFiManager-master\ESPAsyncWiFiManager.cpp:590:29: note: in expansion of macro 'WPS_CONFIG_INIT_DEFAULT'
   esp_wps_config_t config = WPS_CONFIG_INIT_DEFAULT(ESP_WPS_MODE);
                             ^
C:\Users\---\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_wps.h:86:1: error: C99 designator 'model_number' outside aggregate initializer
 }
 ^
C:\Users\---\Documents\Arduino\libraries\ESPAsyncWiFiManager-master\ESPAsyncWiFiManager.cpp:590:29: note: in expansion of macro 'WPS_CONFIG_INIT_DEFAULT'
   esp_wps_config_t config = WPS_CONFIG_INIT_DEFAULT(ESP_WPS_MODE);
                             ^
C:\Users\---\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_wps.h:86:1: error: C99 designator 'model_name' outside aggregate initializer
 }
 ^
C:\Users\---\Documents\Arduino\libraries\ESPAsyncWiFiManager-master\ESPAsyncWiFiManager.cpp:590:29: note: in expansion of macro 'WPS_CONFIG_INIT_DEFAULT'
   esp_wps_config_t config = WPS_CONFIG_INIT_DEFAULT(ESP_WPS_MODE);
                             ^
C:\Users\---\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_wps.h:86:1: error: C99 designator 'device_name' outside aggregate initializer
 }
 ^
C:\Users\---\Documents\Arduino\libraries\ESPAsyncWiFiManager-master\ESPAsyncWiFiManager.cpp:590:29: note: in expansion of macro 'WPS_CONFIG_INIT_DEFAULT'
   esp_wps_config_t config = WPS_CONFIG_INIT_DEFAULT(ESP_WPS_MODE);
                             ^

**Comment by alanswx** [comment]
Let me know if this is fixed with the latest release. I don't love my fix.. but it seems to compile.

**Comment by dmytro-nff** [comment]
Thanks for the quick response!
Your examples now compile fine!
But to test the work of my project, I need more time.
I will inform you within 2-3 days.

**Comment by icandura** [comment]
I have same problem, too!

`Compiling .pioenvs\nodemcuv2\src\main.cpp.o
Linking .pioenvs\nodemcuv2\firmware.elf
.pioenvs\nodemcuv2\libbd1\libESPAsyncWifiManager_ID1438.a(ESPAsyncWiFiManager.cpp.o):(.text._ZN16AsyncWiFiManager8startWPSEv+0x8): undefined reference to `WPS_is_unavailable_in_this_configuration__Please_check_FAQ_or_board_generator_tool'
.pioenvs\nodemcuv2\libbd1\libESPAsyncWifiManager_ID1438.a(ESPAsyncWiFiManager.cpp.o): In function `AsyncWiFiManager::startWPS()':
ESPAsyncWiFiManager.cpp:(.text._ZN16AsyncWiFiManager8startWPSEv+0x20): undefined reference to `WPS_is_unavailable_in_this_configuration__Please_check_FAQ_or_board_generator_tool'
collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\nodemcuv2\firmware.elf] Error 1`

**Comment by alanswx** [comment]
seems broken in this library. Maybe we should pull the WPS stuff out?

**Comment by nadahmed** [comment]
Same problem as icandura. Although this is the first time I'm using this Async version of this library so things might be faulty at my end as well. Using Platform IO with Atom.
> .pioenvs\nodemcuv2\lib880\libESPAsyncWifiManager_ID1438.a(ESPAsyncWiFiManager.cpp.o):(.text._ZN16AsyncWiFiManager8startWPSEv+0x8): undefined reference to `WPS_is_unavai
lable_in_this_configuration__Please_check_FAQ_or_board_generator_tool'
.pioenvs\nodemcuv2\lib880\libESPAsyncWifiManager_ID1438.a(ESPAsyncWiFiManager.cpp.o): In function `AsyncWiFiManager::startWPS()':
ESPAsyncWiFiManager.cpp:(.text._ZN16AsyncWiFiManager8startWPSEv+0x20): undefined reference to `WPS_is_unavailable_in_this_configuration__Please_check_FAQ_or_board_gener
ator_tool'

collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\nodemcuv2\firmware.elf] Error 1
 [ERROR] Took 5.38 seconds

**Comment by arrowcircle** [comment]
Have the same problem.
I tried to install lib locally and comment out WiFi.beginWPSConfig();

It compiles and scans networks, but captive portal does not open with this exception

```
Exception Cause: 28  [LoadProhibited: A load referenced a page mapped with an attribute that does not permit loads]

0x4021efae: strcpy at /Users/igrokhotkov/e/newlib-xtensa/xtensa-lx106-elf/newlib/libc/machine/xtensa/../../../../.././newlib/libc/machine/xtensa/strcpy.S:103
0x4021a858: String::invalidate() at ??:?
0x4021a920: String::copy(char const*, unsigned int) at ??:?
0x4021aa89: String::operator=(char const*) at ??:?
0x4010020c: _umm_free at umm_malloc.c:?
0x4021b0b0: String::substring(unsigned int, unsigned int) const at ??:?
0x4021a858: String::invalidate() at ??:?
0x4021aa5e: String::operator=(String&&) at ??:?
0x4021052c: AsyncBasicResponse::_respond(AsyncWebServerRequest*) at ??:?
0x4021a874: String::~String() at ??:?
0x402105dc: AsyncWebServerResponse::addHeader(String const&, String const&) at ??:?
0x40210a41: AsyncBasicResponse::AsyncBasicResponse(int, String const&, String const&) at ??:?
0x4021b320: operator new(unsigned int) at ??:?
0x4020f4d1: AsyncWebServerRequest::send(AsyncWebServerResponse*) at ??:?
0x4020f428: AsyncWebServerRequest::beginResponse(int, String const&, String const&) at ??:?
0x4021a966: String::String(char const*) at ??:?
0x4020f44a: AsyncWebServerRequest::send(int, String const&, String const&) at ??:?
0x40215a37: AsyncWiFiManager::handleWifi(AsyncWebServerRequest*, unsigned char) at ??:?
0x401006dc: free at ??:?
0x4021a858: String::invalidate() at ??:?
0x4021ccb8: std::_Function_handler<void (AsyncWebServerRequest*), std::_Bind<std::_Mem_fn<void (AsyncWiFiManager::*)(AsyncWebServerRequest*, unsigned char)> (AsyncWiFiManager*, std::_Placeholder<1>, bool)> >::_M_invoke(std::_Any_data const&, AsyncWebServerRequest*) at ??:?
0x40210e24: AsyncCallbackWebHandler::handleRequest(AsyncWebServerRequest*) at ??:?
0x4021118c: AsyncWebServer::_attachHandler(AsyncWebServerRequest*) at ??:?
0x4020ff38: AsyncWebServerRequest::_parseLine() at ??:?
0x4021ac3c: String::concat(char const*) at ??:?
0x402101ca: AsyncWebServerRequest::_onData(void*, unsigned int) at ??:?
0x4020fc76: AsyncWebServerRequest::AsyncWebServerRequest(AsyncWebServer*, AsyncClient*) at ??:?
0x4021c630: std::_Function_base::~_Function_base() at ??:?
0x4021b320: operator new(unsigned int) at ??:?
0x4010663a: millis at ??:?
0x402101f9: std::_Function_handler<void (void*, AsyncClient*, void*, unsigned int), AsyncWebServerRequest::AsyncWebServerRequest(AsyncWebServer*, AsyncClient*)::{lambda(void*, AsyncClient*, void*, unsigned int)#7}>::_M_invoke(std::_Any_data const&, void*, AsyncClient*, void*, unsigned int) at WebRequest.cpp:?
0x4020def8: AsyncClient::_recv(tcp_pcb*, pbuf*, long) at ??:?
0x401069cc: pvPortMalloc at ??:?
0x4020df3c: AsyncClient::_s_recv(void*, tcp_pcb*, pbuf*, long) at ??:?
0x40226f24: tcp_input at /local/users/gauchard/arduino/arduino_esp8266/origin/tools/sdk/lwip2/builder/lwip2-src/src/core/tcp_in.c:435 (discriminator 1)
0x4022b5f4: mem_malloc at /local/users/gauchard/arduino/arduino_esp8266/origin/tools/sdk/lwip2/builder/lwip2-src/src/core/mem.c:136
0x4022ad85: ip4_input at /local/users/gauchard/arduino/arduino_esp8266/origin/tools/sdk/lwip2/builder/lwip2-src/src/core/ipv4/ip4.c:685
0x402242e8: ethernet_input_LWIP2 at /local/users/gauchard/arduino/arduino_esp8266/origin/tools/sdk/lwip2/builder/lwip2-src/src/netif/ethernet.c:182
0x40224123: esp2glue_ethernet_input at /local/users/gauchard/arduino/arduino_esp8266/origin/tools/sdk/lwip2/builder/glue-lwip/lwip-git.c:439
0x402470ca: ethernet_input at /local/users/gauchard/arduino/arduino_esp8266/origin/tools/sdk/lwip2/builder/glue-esp/lwip-esp.c:363
0x402470db: ethernet_input at /local/users/gauchard/arduino/arduino_esp8266/origin/tools/sdk/lwip2/builder/glue-esp/lwip-esp.c:371
0x4023c823: ppPeocessRxPktHdr at ??:?
0x40242917: ets_snprintf at ??:?
0x40000f49: ?? ??:0
0x40000f49: ?? ??:0
0x40000e19: ?? ??:0
0x40001878: ?? ??:0
0x4010441c: call_user_start_local at ??:?
0x40104422: call_user_start_local at ??:?
0x4010000d: call_user_start at ??:?
0x40100764: cont_ret at cont.S.o:?
0x40100705: cont_continue at cont.S.o:?
```

Any ideas how to fix it?

**Comment by icandura** [comment]
I found something about WPS in ESP8266 Arduino Core documentation.
[FAQ -- ESP8266 Arduino Core](https://arduino-esp8266.readthedocs.io/en/latest/faq/readme.html?highlight=2.4.2)
It will be automatically fix when ESP8266 Arduino Core is updated to 2.5.0 .
Or manually open WPS to fix it now.

> **About WPS**
> From release 2.4.2 and ahead, not using WPS will give an exra ~4.5KB in heap.
> In release 2.4.2 only, WPS is disabled by default and the board generator is required to enable it:
> `./tools/boards.txt.py --allowWPS --boardsgen`
> For platformIO (and maybe other build environments), you will also need to add the build flag: -D NO_EXTRA_4K_HEAP
> This manual selection is not needed starting from 2.5.0 (and in git version). WPS is always available, and not using it will give an extra ~4.5KB compared to releases until 2.4.1 included.

**Comment by alanswx** [comment]
Nice -- should we remove the WPS support? I don't think we need it.

**Comment by icandura** [comment]
> Nice -- should we remove the WPS support? I don't think we need it.

I don't need the WPS support, but I'm not sure if anyone else needs it.

**Comment by arrowcircle** [comment]
Problem is it does not work if we remove WPS support

**Comment by alanswx** [comment]
I think this is fixed now.
