### ISSUE TITLE
Captive Portal without AsyncDNS

### ISSUE THREAD

**Issue by wzaggle** [alanswx/ESPAsyncWiFiManager#28]
Apparently without EADNS, the "loop" function was not being called and so dnsServer->processNextRequest(); was also not getting called so Captive Portal was not working.  I added a call to loop() inside the while of startconfigPortal and it works great now.  Thanks...

**Comment by alanswx** [comment]
Can you submit a patch?

**Comment by alanswx** [comment]
I am confused - so if you use AsyncDNS then of course the processNextRequest is not needed (which is why it was commented out from the ESPWifiManager version of the code). Is there a way to conditionally determine whether to call it?   Why aren't you using the async dns?

**Comment by wzaggle** [comment]
There were issues with AsyncDNS and ESP32 that I didn’t have time to resolve.  The processing of the next DNS event has to happen inside a loop without AsyncDNS.  The call is already conditional but is inside of the safeloop function.  That and critical loop get called by the loop function which was not getting called anywhere.  By putting that in the loop waiting for a connection the DNS request is processed and all is good.  I also made some timing changes to get the IP address assigned to the newly connected station to show up in the final info page.  The way all the html is shipped over via scripts makes it hard to debug.  Now by looking at that final page you can know where to go find your connected device if you need it.  Sometimes it just needs Internet to talk to a remote server, but in other cases I need to access the devices local server once it is on the local internet.  Without knowing its IP or having a display on the device to show it, that means going to the router or relying on mDNS which means more software someplace else.  I use mDNS and it works well with Iphones but touchy with PC’s.

**Comment by alanswx** [comment]
Can you create a patch that works with both?
