### ISSUE TITLE
Readme.md contains link to Tzapu examples

### ISSUE THREAD

**Issue by insensitiveclod** [alanswx/ESPAsyncWiFiManager#36]
The Example links in the readme.md file all point to the Tzapu-repo:
(for example : https://github.com/tzapu/WiFiManager/tree/master/examples/OnDemandConfigPortal)

These wont work for ESP32 due to WiFi.h vs ESP8266WiFi.h
The examples included in the repo do account for this; I reckon that the links should've been pointing at this repo's examples, instead)

**Comment by alanswx** [comment]
I need to fix the readme. Feel free
To submit a pull request. Thank you!

**Comment by alanswx** [comment]
I fixed the links.
