### ISSUE TITLE
Problems with ESP32 and ESPAsyncWiFiManager

### ISSUE THREAD

**Issue by franzzi** [alanswx/ESPAsyncWiFiManager#37]
I have troubles to run the sample "AutoConnect" on my ESP32 (NodeMcu32).
I'm using PlatformIO and I'm able to compile and upload the binary to ESP32. I can find the "AutoConnectAP" network and connect to this network, but when I try to connect to the IP 192.168.4.1 nothing happens, and I can't reach the AsyncWiFiManager via browser.
With ESP8266 and PlatformIO the same example works well with PlatformIO with the precondition of using flag _build_flags = -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY_
Does the actual version just works with ESP8266 or is it also tested with ESP32?
BR
franzzi

**Comment by tve** [comment]
FYI, it works just fine with an ESP32 and pio for me. Note that there has been a significant update to the esp32-arduino framework since the original post here.
