### ISSUE TITLE
ESP-32: crash on Wifi scan

### ISSUE THREAD

**Issue by tueddy** [alanswx/ESPAsyncWiFiManager#44]
Hi,

 i get this ESP-32 crash on startup with a simple scetch. Log:

*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Try to connect with saved credentials
*WM: Connection result: 
*WM: 6
*WM: SET AP STA
*WM: 
*WM: Configuring access point... 
*WM: ESP30AEA4730518
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started
*WM: About to scan()
*WM: About to scan()
*WM: Scan done
abort() was called at PC 0x401458bb on core 1

Backtrace: 0x40090450:0x3ffb1c20 0x40090681:0x3ffb1c40 0x401458bb:0x3ffb1c60 0x40145902:0x3ffb1c80 0x40145217:0x3ffb1ca0 0x40145306:0x3ffb1cc0 0x401452bd:0x3ffb1ce0 0x400de7e7:0x3ffb1d00 0x400dea3d:0x3ffb1d60 0x400ded31:0x3ffb1df0 0x400ded89:0x3ffb1e30 0x400d2293:0x3ffb1e70 0x40145e5b:0x3ffb1fb0 0x400927d9:0x3ffb1fd0

Rebooting...
ets Jun  8 2016 00:22:57

exception trace is:

![grafik](https://user-images.githubusercontent.com/11274319/50965517-72030900-14d2-11e9-8962-2ab648d5a8a3.png)

So something went wrong here (ESPAsyncWiFiManager.cpp line 274):

        wifiSSIDs = new WiFiResult[n];

i assume "n" is out of range? Problem in cleanup? Any idea?

using latest revsions..
Best Dirk

**Comment by tueddy** [comment]
OK, i found the problem:

scanNetworks is defined different on ESP-32:

It uses int16_t instead of int16. So my result is negative number of networks =-2

workaround:

ESPAsyncWiFiManager.h:

`  #if defined(ESP8266)
  int           wifiSSIDCount;
  #else
  int16_t       wifiSSIDCount;
  #endif
`

ESPAsyncWiFiManager.c:
`  //display networks in page
  for (int16_t i = 0; i < wifiSSIDCount; i++) {
`

`#if !defined(ESP8266)
    int16_t n = WiFi.scanNetworks();
#else
    int n = WiFi.scanNetworks();
#endif
`

Hope this helps.

**Comment by alanswx** [comment]
Thank you for finding the issue. Can you submit a patch?

**Comment by tueddy** [comment]
Hi kaegi,
your fix #45 solved all the problems/crashes and it seems to work stable now!
Thank you very much for your work!
