### ISSUE TITLE
why you stole tzapu library and copy paste it as your own project

### ISSUE THREAD

**Issue by AndreiD** [alanswx/ESPAsyncWiFiManager#5]
why your Readme looks the same as this one https://github.com/tzapu/WiFiManager

?...just wondering.

**Comment by alanswx** [comment]
this is just an async version of that project. I need to fix the readme.

**Comment by AndreiD** [comment]
fix it, to me it looks like you're stealing the man's work ... thus making you a thief. 
he worked for his library, and you just copy paste it.

you know that you can fork project right ?

**Comment by gabrielklein** [comment]
I don't understand this ticket as the code of tzapu is MIT... and tzapu is even in the "Thank you" of this project.

**Comment by alanswx** [comment]
It was a sloppy copy / paste but I didn't mean to steal it. It just doesn't make sense as a fork since they can't really be merged in a meaningful way.
