### ISSUE TITLE
Using different port other than 80

### ISSUE THREAD

**Issue by gibo77** [alanswx/ESPAsyncWiFiManager#51]
This is more of a question and not an issue.

Can I use other ports? Other than 80? Port 80 conflicts with my other program when I combine the WifiManagerAsync.
`AsyncWebServer server_Wifimanger(80);`

**Comment by alanswx** [comment]
I think it should work on any port.

**Comment by gibo77** [comment]
It still worked in my sketch. I think because the WifiManager is only needed in connecting to Wifi. Basically the WifinManager port 80 is closed after connecting to Wifi.
