### ISSUE TITLE
Why is switch to revert to station/client only mode commented out?

### ISSUE THREAD

**Issue by pfeerick** [alanswx/ESPAsyncWiFiManager#52]
Just wondering if this was done due to a bug/issue, or was something that didn't get finished. I love this library, as it allows me to have the wifi non-blocking through the modeless functionality, and able to use ESPAsyncWebServer as well, but I'd rather the ESPs AP shut down if a connection to the configured AP is established, rather than leave it running all the time. 

https://github.com/alanswx/ESPAsyncWiFiManager/blob/3e447fff21b0d0e85d8498442356914c1dbfdb5c/ESPAsyncWiFiManager.cpp#L427-L429

**Comment by alanswx** [comment]
It was a long time ago but I don’t think it worked the way I expected. Why don’t you try it and see if you can get it working and submit a pull request. Thanks. If not add some comments on the behavior to this issue. Things might work better now. The underlying libraries are a lot newer.

**Comment by pfeerick** [comment]
Really, I should try it myself? You won't do it for me? :stuck_out_tongue: Am working on a project where I didn't want to break the WiFi just yet (yes, walking up stairs to retrieve that module when WiFi breaks OTA is a real hassle. :laughing:  

I'll give it a whirl on another board, and see what happens. I wonder if it was something to do with just switching between the wifi modes, instead of shutting down the AP and then starting back up in station mode. As a note for myself for later, I'll try the code as it is, and then see what happens with the following code. 

```
WiFi.softAPdisconnect();
WiFi.disconnect();
WiFi.mode(WIFI_STA);
```

I might also do another PR with an example showing how you can use the blocking mode with a simple ESPAsyncWebServer project, as that was part of the reason I went the non-blocking route... I didn't realise it was that easy to use the two together...

**Comment by alanswx** [comment]
It is hard for me to context switch the code back in my brain and get my esp8266 environment all setup again. I did a big update and bunch of bug fixes 6 months ago (maybe?). Thanks for helping!

**Comment by pfeerick** [comment]
Ok, me not afraid to admit me _stoopid_! Mesa _not read function names properly_. 

`startConfigPortalModeless`

aka the config portal is SUPPOSED to stay running. :man_facepalming: 

Ah well, I'll do some spring cleaning anyway... a bit of code reformatting, URL corrections and another example or two is in need since I'm ferreting around in the guts of the library. I'll be back in a few days with a PR :wink: 

btw... A big thanks for doing your ESPAsyncWebServer version of WifiManager... the other forks I tried seemed to work at first, but bummed out when I put them to the test and reset the wifi credentials. In other words, they could connect to a pre-configured wifi access point with no problems, but didn't actually serve up the config portal when it was needed. So I'm gradually in the process of switching over to your library whenever I do any new code that uses ESPAsyncWebServer internally.

**Comment by HamzaHajeir** [comment]
Hi

I am testing up my esp with ModelessConnect example.

But i got no connection to network (after configuring network via Captive portal, And it comes back to AP again.

I've everything up-to-date
library version : 0.21
esp8266 core : 2.5.2
Arduino IDE 1.8.9

Is there anything missing in example file ?
