### ISSUE TITLE
WiFi credentials lost after first connection fail

### ISSUE THREAD

**Issue by gmag11** [alanswx/ESPAsyncWiFiManager#57]
I'm using this library in some of my projects. I've noticed that, if configured SSID is not active when calling `autoconnect()` SSID is reset.
My code to initialise wifiManager is [here](https://github.com/gmag11/EnigmaIOT/blob/master/MqttBridge/MqttBridge.ino#L151-L193).

This is the log I've got. 1st attempt it shows it tries to connect to my SSID, but following trials show an empty SSID string.

```
*WM: Adding parameter
*WM: mqttserver
*WM: Adding parameter
*WM: mqttport
*WM: Adding parameter
*WM: mqttuser
*WM: Adding parameter
*WM: mqttpass
*WM: Adding parameter
*WM: mqtttopic
[186] 38096 free (configWiFiManager:179) Connecting to WiFi: MY_SSID
*WM: 
*WM: AutoConnect Try No.:
*WM: 0
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 1
*WM: SET AP STA
*WM: 
*WM: Configuring access point... 
*WM: EnigmaIoTMQTTBridge2410ac
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started
*WM: About to scan()
*WM: About to scan()
*WM: Scan done
*WM: About to scan()
*WM: About to scan()
*WM: Scan done
*WM: About to scan()
*WM: About to scan()
*WM: Scan done
*WM: About to scan()
*WM: About to scan()
*WM: Scan done
*WM: DUP AP: WLAN_11F3
*WM: About to scan()
*WM: About to scan()
*WM: Scan done
*WM: DUP AP: WLAN_11F3
[69922] 34792 free (setup:252) Error connecting to WiFi

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
ve56aed65
~ld

*WM: Adding parameter
*WM: mqttserver
*WM: Adding parameter
*WM: mqttport
*WM: Adding parameter
*WM: mqttuser
*WM: Adding parameter
*WM: mqttpass
*WM: Adding parameter
*WM: mqtttopic
[190] 36584 free (configWiFiManager:179) Connecting to WiFi: 
*WM: 
*WM: AutoConnect Try No.:
*WM: 0
*WM: Connecting as wifi client...
*WM: Try to connect with saved credentials
*WM: Connection result: 
*WM: 0
*WM: SET AP STA
*WM: 
*WM: Configuring access point... 
*WM: EnigmaIoTMQTTBridge2410ac
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started
*WM: About to scan()
*WM: About to scan()
*WM: Scan done
*WM: DUP AP: WLAN_11F3
*WM: About to scan()
*WM: About to scan()
*WM: Scan done
*WM: About to scan()
*WM: About to scan()
*WM: Scan done
*WM: About to scan()
*WM: About to scan()
*WM: Scan done
*WM: About to scan()
*WM: About to scan()
*WM: Scan done
*WM: DUP AP: WLAN_11F3
[60371] 34680 free (setup:252) Error connecting to WiFi

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
ve56aed65
~ld
```

It keeps so until I reconfigure WiFi credentials using web portal.

I'm not sure if I am doing something wrong.

**Comment by gmag11** [comment]
I've tested to comment [L490](https://github.com/alanswx/ESPAsyncWiFiManager/blob/master/ESPAsyncWiFiManager.cpp#L490), [L571](https://github.com/alanswx/ESPAsyncWiFiManager/blob/master/ESPAsyncWiFiManager.cpp#L571) and [L585](https://github.com/alanswx/ESPAsyncWiFiManager/blob/master/ESPAsyncWiFiManager.cpp#L585).

Doing so, `autoconnect()` connects when AP is available again.

`WiFi.disconnect()` erases stored config, so next `WiFi.begin()` will fail to connect.

**Comment by gmag11** [comment]
Check https://github.com/tzapu/WiFiManager/issues/280.

You can add WiFi.persistent(false) before WiFi.disconnect() and WiFi.persistent() after, so that configuration in flash gets not deleted.

**Comment by gmag11** [comment]
Finally, this only affects to `WiFi.connect()`on ESP8266 platform. Using Non-OS SDK disconnect function instead to get required behaviour.

**Comment by gmag11** [comment]
Instead using `WiFi.disconnect()`, on ESP8266 it is recommended to use this code:
```
ETS_UART_INTR_DISABLE ();
wifi_station_disconnect ();
ETS_UART_INTR_ENABLE ();
```
as it do not deletes stored WiFi credentials. This is probably a bug in ESP8266 Arduino core.

It is confirmed that on ESP32 `WiFi.disconnect()` works fine.

**Comment by Paytah232** [comment]
![image](https://user-images.githubusercontent.com/44075588/80280943-dc34d100-874a-11ea-90e9-653c548992fb.png)
I think I might be having the same issue as you here @gmag11...
I am using an ESP32 Sparkfun Thingy. I have a couple thousand lines of code at this point, but the thing failing me in the wifimanager and it prints messages the same as yours did. How exactly did you solve this problem? Thanks in advance!

**Comment by gmag11** [comment]
Current version works flawlessly for me. What is your expected behabiour?
