### ISSUE TITLE
ESP8266 I can't get the wifi credentials to be forgotten

### ISSUE THREAD

**Issue by MassiPi** [alanswx/ESPAsyncWiFiManager#82]
Hello,
i tried to erase the wifi credentials in a list of ways:
- wifiManager.resetSettings();
- WiFi.disconnect(true);
- WiFi.disconnect();

in all cases, i get the disconnection from the wifi network, but on reboot it reconnects.

i'm sure in the past this was working (i just had to fight with esp32 for this, but on esp8266 it used to work!) so i wonder if any problem rose with new versions.
I'm using 3.0.0, anyone else?

Thanks

**Comment by dansiebert** [comment]
I had the same problems with PlatformIO and espressif8266@3.0.0. I switched back to espressif8266@2.6.3. That’s how it works.

**Comment by MassiPi** [comment]
strangely i haven't seen any bug report on espressif git repository.. i'll try to ask also there :)
I don't think this can be something up to platformio (even if yes, i'm also using it), did you try also with arduino ide?
thanks!

**Comment by dansiebert** [comment]
I adapted my code for the Arduino IDE and compiled it with Core 3.0.0. Then the behavior shows itself. It forgets the WiFi connection data every time it reboots.

**Comment by MassiPi** [comment]
sorry, i haven't understood. I can't get the credentials to be forgotten, now you are telling me that it forgets them at any reboot?

**Comment by MassiPi** [comment]
lol so we have the very opposite problem. Very nice! 
and i'm also using wemos D1 mini..
i'll try erasing the flash, as you say.. thanks!

**Comment by MassiPi** [comment]
i can confirm your problem, once i totally erased the flash, wifi config can't be stored anymore.
So it seems a problem of 3.0.0
Strange i see no bug reported

**Comment by hmronline** [comment]
@MassiPi from what I see in the code this was already fixed, right ?
Could you please close this issue ? thanks!

**Comment by MassiPi** [comment]
oh yes sure, this came from a different approach in esp8266 3.0.0
