### ISSUE TITLE
Build Failure ESPAsyncWiFiManager.cpp:398:51

### ISSUE THREAD

**Issue by bmoniey** [alanswx/ESPAsyncWiFiManager#89]
C:\Users\moran\.platformio\packages\framework-arduinoespressif32\cores\esp32/WString.h:358:9: note:   conversion of argument 1 would be ill-formed:
.pio\libdeps\esp32doit-devkit-v1\ESPAsyncWiFiManager\src\ESPAsyncWiFiManager.cpp:398:51: error: invalid conversion from 'const __FlashStringHelper*' to 'long unsigned int' [-fpermissive]
             DEBUG_WM(F("DUP AP: ") + wifiSSIDs[j].SSID);
                                                   ^

Corrected by replacing with:
            DEBUG_WM("DUP AP: " + wifiSSIDs[j].SSID);

**Comment by alanswx** [comment]
Can you send me a patch? Thank you.

**Comment by hmronline** [comment]
I will fix it in the following hours

**Comment by hmronline** [comment]
@bmoniey I've just submitted a PR that includes a fix for this.
Could you please test the new version once it's available and close this issue if everything is ok ? thank you!

**Comment by bmoniey** [comment]
@hmronline  I just tried out your pull request #90. Loaded it to an ESP32 and works as expected thanks!
@hmronline Many thanks for your work. Cheers.
